---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
      - php
  eslint:
    enabled: true
  fixme:
    enabled: true
  phpmd:
    enabled: true
    file_extensions: php
    rulesets: Resources/phpmd-rulesets/rulset.xml
ratings:
  paths:
  - "**.js"
  - "**.php"
exclude_paths:
  - vendor/*
  - Resources/*
