---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
      - php
  eslint:
    enabled: true
  fixme:
    enabled: true
  phpmd:
    enabled: true
    config:
      file_extensions: php
      rulesets: vendor/smile/magento2-coding-standards/phpmd-rulesets/rulset.xml
ratings:
  paths:
  - "**.js"
  - "**.php"
exclude_paths:
  - src/*/Test
  - vendor/*
  - Resources/*
