language: php

php:
- '5.6'
- '7.0'

install:
    - mkdir -p app/etc
    - echo "{\"http-basic\":{\"repo.magento.com\":{\"username\":\"${MAGENTO_USERNAME}\",\"password\":\"${MAGENTO_PASSWORD}\"}}}" > auth.json
    - composer install --prefer-dist

cache:
  directories:
    - $HOME/.composer/cache

script:
    - vendor/squizlabs/php_codesniffer/scripts/phpcs --standard=Resources/phpcs-standards/SmileElasticSuite --extensions=php src/
    - vendor/phpmd/phpmd/src/bin/phpmd src text Resources/phpmd-rulesets/rulset.xml
